[package]
name = "datagen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
enumset = "1.1.3"
game = { path = "../game" }
rmp-serde = "1.3.0"
serde = "1.0.209"
smallvec = { version = "1.13.2", features = ["serde"] }
