[package]
name = "ordinal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.3"
enumset = "1.1.3"
game = { path = "../game" }
once_cell = "1.19.0"
parking_lot = "0.12.3"
rand = "0.8.5"
