[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
firefly = { path = "../firefly" }
futures = "0.3.30"
tokio = { version = "1.39.3", features = ["full"] }
serde = "1.0.209"
serde_json = "1.0.127"
enumset = "1.1.5"
