[package]
name = "gen_cc"
version = "0.1.0"
edition = "2021"

[dependencies]
enumset = "1.1.3"
game = { path = "../game" }
parking_lot = "0.12.3"
serde_json = "1.0.127"
tokio = { version = "1", features = ["full"] }
