[package]
name = "firefly"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo-herd = "0.1.2"
dashmap = "5.5.3"
enumset = "1.1.3"
futures = "0.3.30"
game = { path = "../game" }
once_cell = "1.19.0"
parking_lot = "0.12.3"
rand = "0.8.5"
serde = "1.0.208"
serde_json = "1.0.125"
